-- ─────────────────────────────────────────────────────────────────────────────
-- Seed vy_ref_sequences from SiteForms RFI and Site Note records.
--
-- These were omitted from the initial universal sequence migration because
-- their refs live in vy_site_forms.extra_data (JSONB), not a dedicated column,
-- and they were generated by a module-scope in-memory counter (FormBuilder.tsx)
-- that was incorrectly believed to be non-sequential.
--
-- Scope: org_id (uuid cast to text) — RFI and Site Note refs are
-- unique within the organisation regardless of project, matching the
-- behaviour the original counter had within a single browser session.
-- ─────────────────────────────────────────────────────────────────────────────

-- RFI refs stored in vy_site_forms.extra_data->>'rfiRef' (e.g. "RFI-010")
INSERT INTO vy_ref_sequences (scope_id, prefix, next_val)
SELECT
  org_id::text,
  'RFI',
  COALESCE(MAX(NULLIF(regexp_replace(extra_data->>'rfiRef', '[^0-9]', '', 'g'), '')::integer), 0) + 1
FROM vy_site_forms
WHERE type = 'RFI'
  AND extra_data ? 'rfiRef'
  AND org_id IS NOT NULL
GROUP BY org_id
ON CONFLICT (scope_id, prefix)
  DO UPDATE SET next_val = GREATEST(vy_ref_sequences.next_val, EXCLUDED.next_val);

-- Site Note refs stored in vy_site_forms.extra_data->>'snRef' (e.g. "SN-0001")
INSERT INTO vy_ref_sequences (scope_id, prefix, next_val)
SELECT
  org_id::text,
  'SN',
  COALESCE(MAX(NULLIF(regexp_replace(extra_data->>'snRef', '[^0-9]', '', 'g'), '')::integer), 0) + 1
FROM vy_site_forms
WHERE type = 'Site Note'
  AND extra_data ? 'snRef'
  AND org_id IS NOT NULL
GROUP BY org_id
ON CONFLICT (scope_id, prefix)
  DO UPDATE SET next_val = GREATEST(vy_ref_sequences.next_val, EXCLUDED.next_val);
